### ISSUE TITLE
code style/linting rules and enforcement

### ISSUE THREAD

**Issue by glennhartmann** [GoogleChromeLabs/llaminator#15]
I imagine there are plenty of node-based linters we can hook up to our build process. Is there a way to enforce it from github-side for pull requests?

@beverloo @andreban

**Comment by andreban** [comment]
This is the GitHub Workflow we use in Bubblewrap: https://github.com/GoogleChromeLabs/bubblewrap/blob/main/.github/workflows/nodejs.yml. For the linter, I usually go for EsLint with the google-eslint rules (with tweaks): https://github.com/google/eslint-config-google

**Comment by glennhartmann** [comment]
first step: https://github.com/GoogleChromeLabs/llaminator/pull/64
