### ISSUE TITLE
ServiceWorker is broken

### ISSUE THREAD

**Issue by glennhartmann** [GoogleChromeLabs/llaminator#19]
See https://github.com/GoogleChromeLabs/llaminator/pull/17

**Comment by glennhartmann** [comment]
it was so difficult to figure out that all this needs is `type: 'module'` on the service worker registration. Very very unintuitive and opaque error message.

**Comment by jeffposnick** [comment]
I wouldn't recommend using `type: 'module'` at the moment, as browser support (specifically in Firefox) isn't universal: https://web.dev/es-modules-in-sw/#browser-support

**Comment by glennhartmann** [comment]
> browser support (specifically in Firefox) isn't universal: https://web.dev/es-modules-in-sw/#browser-support

:(
