### ISSUE TITLE
`npm run-script build` output doesn't work

### ISSUE THREAD

**Issue by glennhartmann** [GoogleChromeLabs/llaminator#24]
See https://github.com/GoogleChromeLabs/llaminator/pull/22

The error message says that index.ts's "MIME type ('video/mp2t') is not executable."

I'm guessing that's because we're trying to include a ".ts" file as a script, and .ts is being misinterpreted.

**Comment by beverloo** [comment]
Seems to work fine here:

```
$ npm run-script build

> llaminator@0.0.1 build
> rollup -c rollup.config.mjs


src/index.ts → dist...
created dist in 101ms

src/sw.ts → dist...
created dist in 346ms
```

**Comment by glennhartmann** [comment]
sorry, to be more specific - the `build` step succeeds, but then serving up the output directory with a static server will give you a runtime error when `index.html` tries to include `index.ts` as a script
