### ISSUE TITLE
discussion: overall project, filesystem, build and dev environment, etc. thread

### ISSUE THREAD

**Issue by glennhartmann** [GoogleChromeLabs/llaminator#34]
I've noticed that the following PRs have been trying to deal with just getting a build system actually fully working with typescript and service workers (0 new actual functionality in the app):

* https://github.com/GoogleChromeLabs/llaminator/pull/13
* https://github.com/GoogleChromeLabs/llaminator/pull/14
* https://github.com/GoogleChromeLabs/llaminator/pull/17
* https://github.com/GoogleChromeLabs/llaminator/pull/18
* https://github.com/GoogleChromeLabs/llaminator/pull/22
* https://github.com/GoogleChromeLabs/llaminator/pull/26
* https://github.com/GoogleChromeLabs/llaminator/pull/29
* https://github.com/GoogleChromeLabs/llaminator/pull/32
* https://github.com/GoogleChromeLabs/llaminator/pull/33
* another one I'm currently working on to fix Workbox as part of https://github.com/GoogleChromeLabs/llaminator/issues/19

What in the world is going on with this ecosystem?

I *think* this is a (roughly) exhaustive description of our ideal state:

* dev server that can auto-reload when there are changes to the filesystem
* a way to "export" a copy of the post-build codebase, suitable for hosting elsewhere (including static file servers)
* typescript for both main site code and service worker code, enforcing strict type checks
* some amount of code-sharing ability between the main site code and service worker code (WebShareTarget, as a concrete example, is a place where code sharing would make a lot of sense)
* ability to use 3rd party packages (ideally via npm) in both main site and service worker
* (feel free to add more to this list)

Here's a summary of issues we've encountered along the way (I will probably forget some):

* [Workbox](https://developers.google.com/web/tools/workbox) requires either bundling, [Service Worker modules](https://web.dev/es-modules-in-sw/), or an `importScripts()` from a CDN
  * Service Worker modules have compatibility issues
    * `Uncaught SyntaxError: Cannot use import statement outside a module` is such an unhelpful error message at sw installation time
  * bundling is generally the ideal option (failing Service Worker modules) for both Workbox and other npm packages, but [@web/dev-server](https://www.npmjs.com/package/@web/dev-server) can't auto-reload bundles
  * the CDN doesn't come with types built-in by default, and [@types/workbox-sw](https://www.npmjs.com/package/@types/workbox-sw) isn't working for me
* @web/dev-server serves files with their original extensions (like `*.ts`) rather than their "compiled" extensions (`*.js`). But when doing a static build, browsers (or maybe just Chrome?) can't seem to figure out that ".ts" isn't 'video/mp2t' (https://github.com/GoogleChromeLabs/llaminator/issues/24)
* different servers have different root directories - maybe there's a way to make all the paths properly relative, but so far we've ended up with a hack as part of the build process
* I'm not entirely convinced that @web/dev-server (and maybe even the rollup config) is actually using our tsconfig.json. Maybe it's [ESBuild](https://esbuild.github.io/)'s fault? No idea.
  * we also may need(?) to mess around with our filesystem and configs like https://github.com/jakearchibald/typescript-worker-example to get the tsconfig.json to work properly for both "normal" code and service worker
* package-lock.json
* it's not entirely clear which type of storage we should be using (https://github.com/GoogleChromeLabs/llaminator/issues/20, https://github.com/GoogleChromeLabs/llaminator/issues/21)
* at first it seemed like `declare var self: ServiceWorkerGlobalScope` was required to make `self` work properly in typescript in the service worker. Now, for some reason, it's telling me I can't redeclare `self` (currently its type is `WorkerGlobalScope & typeof globalThis` as set by the `webworker` lib)
* code sharing between main code and sw is difficult and complicated. sw, generally, doesn't support modules, which is what we should be using for the main code. sw modules have compatibility issues. Some sort of bundling build system may(?) be able to mitigate this (see note about @web/dev-server not playing nice with that) but then it's still tricky to figure out which parts are sharable - for example, what type is `self`? Could change depending on the context. "main" code and sw code are generally built with different libs.

**Comment by beverloo** [comment]
Thank you for the thorough issue!

I've sent a PR to sort this all out: https://github.com/GoogleChromeLabs/llaminator/pull/36

> Workbox requires either bundling, Service Worker modules, or an importScripts() from a CDN

We should avoid importing scripts from a CDN if we can. There's been (in)famous outages regarding that, but it also reduces the opportunity to automatically minimize filesizes.

> @web/dev-server serves files with their original extensions (like *.ts) rather than their "compiled" extensions (*.js).

Yeah that's moot. Fixed in the PR.

> different servers have different root directories

Do we want to support non-root installations? I'm not convinced there's value in that, it won't match production and maintenance can be a pain, as subtle issues are easy to create. I've given up on this in the PR, we can re-add (in a proper way) if desired.

> package-lock.json

"This file is intended to be committed into source repositories" - https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json

I have no particularly strong opinion on this, and would rather just follow what NPM's maintainers say.

> it's not entirely clear which type of storage we should be using

That seems unrelated to the build system?

> code sharing between main code and sw is difficult and complicated

Addressed in the PR. We'll want to add a "common" directory of sorts to be explicit about what code can be pulled in to both bundles, to avoid accidentally pulling in more than intended. I think that a little bit of duplication generally is fine.

**Comment by glennhartmann** [comment]
> Do we want to support non-root installations? I'm not convinced there's value in that, it won't match production and maintenance can be a pain, as subtle issues are easy to create. I've given up on this in the PR, we can re-add (in a proper way) if desired.

The only reason I want it, really, is for something like https://glennhartmann.github.io/llaminator - it's nice to have somewhere to deploy it (even in a far-from-complete state) just to make sure things work in a prod-like environment, without localhost or port forwarding.

I'm sure we can find another place to host static content for free at an origin root, though. [glitch.com](https://glitch.com) jumps to mind.

> > package-lock.json
> 
> "This file is intended to be committed into source repositories" - [docs.npmjs.com/cli/v8/configuring-npm/package-lock-json](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json)
> 
> I have no particularly strong opinion on this, and would rather just follow what NPM's maintainers say.

Yeah, I know, I just don't love the fact that commits often include random essentially-opaque blobs. It's especially annoying if some contributors are using npm v7+, and others aren't, because then it will oscillate between v1 package-lock.json and v2 package-lock.json formats (https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion). I suspect that may also be the reason behind why https://github.com/GoogleChromeLabs/llaminator/pull/26 was necessary. /shrug

> > it's not entirely clear which type of storage we should be using
> 
> That seems unrelated to the build system?

Yeah, originally I intended this issue to also be more generally about the web ecosystem and unclear documentation, etc, but it did end up being pretty skewed towards build-related issues.

**Comment by glennhartmann** [comment]
> Yeah, originally I intended this issue to also be more generally about the web ecosystem and unclear documentation, etc, but it did end up being pretty skewed towards build-related issues.

And to be clear, this wasn't supposed to be a critique of the particular build system we were using, but more of a "these are difficult things to deal with in new projects, and the web needs to get better at making them less painful"

**Comment by beverloo** [comment]
> The only reason I want it, really, is for something like https://glennhartmann.github.io/llaminator - it's nice to have somewhere to deploy it (even in a far-from-complete state) just to make sure things work in a prod-like environment, without localhost or port forwarding.

I'm sure there's some CI that supports this, alternatively Netlify might be an option. That said, I guess this doesn't strictly count as a personal project 😛 

> Yeah, I know, I just don't love the fact that commits often include random essentially-opaque blobs. It's especially annoying if some contributors are using npm v7+, and others aren't, because then it will oscillate between v1 package-lock.json and v2 package-lock.json formats (https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion).

We can require a minimum NPM version if you'd like to avoid this.
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines

> I suspect that may also be the reason behind why #26 was necessary. /shrug

That'd be a great reason for requiring a minimum NPM version 😃 

>> Yeah, originally I intended this issue to also be more generally about the web ecosystem and unclear documentation, etc, but it did end up being pretty skewed towards build-related issues.
> And to be clear, this wasn't supposed to be a critique of the particular build system we were using, but more of a "these are difficult things to deal with in new projects, and the web needs to get better at making them less painful"

Yeah, it's particularly hard to navigate, particularly in a stage when we're not ready to commit to specific technologies.

**Comment by glennhartmann** [comment]
> I'm sure there's some CI that supports this, alternatively Netlify might be an option. That said, I guess this doesn't strictly count as a personal project 😛

It's a personal _fork_ of a project...
