### ISSUE TITLE
Consider cross-device syncing.

### ISSUE THREAD

**Issue by PEConn** [GoogleChromeLabs/llaminator#55]
It would be really nice if there were a way for users to access their images across devices. This would also mean that we have persistence if the user's local storage is cleared.

**Comment by glennhartmann** [comment]
Closing this issue in favour of making finer-grained issues organized under https://github.com/GoogleChromeLabs/llaminator/milestone/1

**Comment by glennhartmann** [comment]
Split into #102, #103, #104, #105, #106
