### ISSUE TITLE
External contributor - first impression

### ISSUE THREAD

**Issue by finnurbreki** [GoogleChromeLabs/llaminator#56]
These are the notes I took, at the beginning of the year 2022, documenting my first impressions of getting the project up and running, for someone (like myself) who has no knowledge of the project, and perhaps wants to contribute. Consider it a stress test on the installation procedure.

Maybe none of the stuff mentioned below would be classified as bugs, maybe some would. But this documents the process I went through and what I discovered along the way. Maybe it provides some insight.

First thing I discovered was I didn't have npn installed
`sudo apt install npm` fixed that.

I then downloaded the zip from github and placed the code into my code directory.

```
~/code$ node -v
v10.19.0
~/code$ npm -v
6.14.4
```

So far so good, I guess. Let's try...

`~/code/llaminator-main$ npm install`

However, the first message is a conflict message. Not the start I was hoping for. Can we git rid of that?

```
npm WARN conflict A git conflict was detected in package-lock.json. Attempting to auto-resolve.
npm WARN conflict To make this happen automatically on git rebase/merge, consider using the npm-merge-driver:
npm WARN conflict $ npx npm-merge-driver install -g
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

Next, according to the instructions is to serve the site from an http server, by doing...

```
~/code/llaminator-main$ npm run-script serve

> llaminator@0.0.1 serve /home/finnur/code/llaminator-main
> webpack serve --open --mode=development

sh: 1: webpack: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! llaminator@0.0.1 serve: `webpack serve --open --mode=development`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the llaminator@0.0.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/finnur/.npm/_logs/2022-01-05T17_16_53_308Z-debug.log
```

Should webpack be listed as a pre-requisite in the instructions?

`~/code/llaminator-main$ npm install webpack` succeeds. Let's try again...

```
~/code/llaminator-main$ npm run-script serve

> llaminator@0.0.1 serve /home/finnur/code/llaminator-main
> webpack serve --open --mode=development

[webpack-cli] /home/finnur/code/llaminator-main/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^
SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.getServerTransport (/home/finnur/code/llaminator-main/node_modules/webpack-dev-server/lib/Server.js:1191:28)
    at Server.createWebSocketServer (/home/finnur/code/llaminator-main/node_modules/webpack-dev-server/lib/Server.js:1757:38)
    at Server.start (/home/finnur/code/llaminator-main/node_modules/webpack-dev-server/lib/Server.js:2305:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! llaminator@0.0.1 serve: `webpack serve --open --mode=development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the llaminator@0.0.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/finnur/.npm/_logs/2022-01-05T17_32_58_219Z-debug.log
```

I'm guessing this is not expected? :)

**Comment by glennhartmann** [comment]
I'm pretty sure that at least part of this is because the node/npm versions you're using are way older than what we use. Please let me know if this update to the readme helps: https://github.com/GoogleChromeLabs/llaminator/pull/57/files

**Comment by glennhartmann** [comment]
> 
> Should webpack be listed as a pre-requisite in the instructions?
> 

webpack is already listed as a dev dependency here https://github.com/GoogleChromeLabs/llaminator/blob/main/package.json#L31, so it _should_ be automatically installed with `npm install`. Hopefully this, too, is solved by using a newer version of NPM and Node.

**Comment by finnurbreki** [comment]
Yeah, updating worked. Thanks!
