### ISSUE TITLE
style guidelines discussion thread

### ISSUE THREAD

**Issue by glennhartmann** [GoogleChromeLabs/llaminator#65]
https://github.com/GoogleChromeLabs/llaminator/pull/64 landed, so we have some default style rules. The question is, do we like them?

Leaving for open discussion for the moment.

**Comment by PEConn** [comment]
I ran `eslint --fix` and uploaded the result as PR #66, the following issues couldn't be automatically fixed:

```
/Users/peconn/github/llaminator/service_worker/index.ts
  20:1  error  This line has a length of 87. Maximum allowed is 80  max-len
  24:7  error  'mainDBName' is assigned a value but never used      no-unused-vars
  25:7  error  'objStoreName' is assigned a value but never used    no-unused-vars
  26:7  error  'mainImageName' is assigned a value but never used   no-unused-vars
  46:1  error  Missing JSDoc comment                                require-jsdoc

/Users/peconn/github/llaminator/src/components/llama-header.ts
  21:8   error  Missing JSDoc comment                                require-jsdoc
  26:19  error  Missing JSDoc comment                                require-jsdoc
  30:9   error  Missing JSDoc comment                                require-jsdoc
  34:1   error  This line has a length of 90. Maximum allowed is 80  max-len

/Users/peconn/github/llaminator/src/components/llama-select-fab.ts
  21:8   error  Missing JSDoc comment  require-jsdoc
  24:19  error  Missing JSDoc comment  require-jsdoc
  28:20  error  Missing JSDoc comment  require-jsdoc
  42:9   error  Missing JSDoc comment  require-jsdoc

/Users/peconn/github/llaminator/src/index.ts
  49:1  error  This line has a length of 122. Maximum allowed is 80  max-len
  52:1  error  This line has a length of 109. Maximum allowed is 80  max-len
  52:1  error  Missing JSDoc comment                                 require-jsdoc
  61:1  error  This line has a length of 143. Maximum allowed is 80  max-len
  61:1  error  Missing JSDoc comment                                 require-jsdoc
  77:1  error  This line has a length of 92. Maximum allowed is 80   max-len
  77:1  error  Missing JSDoc comment                                 require-jsdoc
  88:1  error  This line has a length of 90. Maximum allowed is 80   max-len
  88:1  error  Missing JSDoc comment                                 require-jsdoc

/Users/peconn/github/llaminator/src/storage.ts
   66:8   error  Missing JSDoc comment                                require-jsdoc
   69:22  error  Missing JSDoc comment                                require-jsdoc
   74:22  error  Missing JSDoc comment                                require-jsdoc
   88:12  error  Missing JSDoc comment                                require-jsdoc
  111:13  error  Missing JSDoc comment                                require-jsdoc
  115:16  error  Missing JSDoc comment                                require-jsdoc
  125:12  error  Missing JSDoc comment                                require-jsdoc
  135:21  error  Missing JSDoc comment                                require-jsdoc
  142:1   error  This line has a length of 93. Maximum allowed is 80  max-len
  142:15  error  Missing JSDoc comment                                require-jsdoc
  143:29  error  Expected an error object to be thrown                no-throw-literal
  147:18  error  Expected an error object to be thrown                no-throw-literal

/Users/peconn/github/llaminator/tests/puppeteer.test.js
  17:1  error  This line has a length of 82. Maximum allowed is 80  max-len
  27:1  error  This line has a length of 86. Maximum allowed is 80  max-len
```

Personally I'm fine with all of the suggestions, with the exception of `object-curly-spacing` (no spaces after '{' or before '}') and possibly `require-jsdoc` (more info about possible checks [here](https://eslint.org/docs/rules/).

**Comment by glennhartmann** [comment]
## Unorganized thoughts:

### from https://github.com/GoogleChromeLabs/llaminator/pull/66/files, in order:

* `port: 8888` -> `port: 8888,` and similar: good
* `import { StaleWhileRevalidate } from 'workbox-strategies';` -> `import {StaleWhileRevalidate} from 'workbox-strategies';` and similar: I feel like this will be unpopular. Personally I kind of think it makes sense, but from what I've seen, the spaces are fairly common in this world. I defer to others.
* `declare var self: ServiceWorkerGlobalScope;` -> `declare let self: ServiceWorkerGlobalScope;`: good
* adding semicolons: good
* `createRenderRoot() { return this; }` -> `createRenderRoot() {\n    return this;\n  }`: seems unnecessary, I don't see an issue with a one-line function if it's this trivial
* adding `{}` around if blocks, even when it's not strictly necessary: I like it. Let's not goto fail
* only 1 space between code and comments: this way is my personal preference, but it's quite low on my list of things to care about
* `:` of ternary being on the end of the previous line, vs the beginning of the next line: again, very low on my priorities, I could go either way

### un-auto-fixable items:
* `20:1  error  This line has a length of 87. Maximum allowed is 80  max-len`, etc: having a line length limit is probably a good thing. Personally I think 80 is lower than it needs to be. 100 or even maybe 120(?) would be my personal preference.
* `46:1  error  Missing JSDoc comment                                require-jsdoc`: it's annoying, but probably valuable
* ` 143:29  error  Expected an error object to be thrown                no-throw-literal`: haven't decided yet

### other stuff

There are lots of custom rules in https://github.com/GoogleChromeLabs/bubblewrap/blob/main/.eslintrc.json that we could potentially steal, but I haven't looked through them yet

**Comment by beverloo** [comment]
> ## Unorganized thoughts:
> ### from https://github.com/GoogleChromeLabs/llaminator/pull/66/files, in order:
> * `port: 8888` -> `port: 8888,` and similar: good
> * `import { StaleWhileRevalidate } from 'workbox-strategies';` -> `import {StaleWhileRevalidate} from 'workbox-strategies';` and similar: I feel like this will be unpopular. Personally I kind of think it makes sense, but from what I've seen, the spaces are fairly common in this world. I defer to others.
> * `declare var self: ServiceWorkerGlobalScope;` -> `declare let self: ServiceWorkerGlobalScope;`: good
> * adding semicolons: good
> * `createRenderRoot() { return this; }` -> `createRenderRoot() {\n    return this;\n  }`: seems unnecessary, I don't see an issue with a one-line function if it's this trivial
> * adding `{}` around if blocks, even when it's not strictly necessary: I like it. Let's not goto fail
> * only 1 space between code and comments: this way is my personal preference, but it's quite low on my list of things to care about
> * `:` of ternary being on the end of the previous line, vs the beginning of the next line: again, very low on my priorities, I could go either way

Agreed on all counts. I _really_ like the extra spaces in e.g. `import { StaleWhileRevalidate } from ...`, that's the only one I would consider arguing for in this list.

> ### un-auto-fixable items:
> * `20:1  error  This line has a length of 87. Maximum allowed is 80  max-len`, etc: having a line length limit is probably a good thing. Personally I think 80 is lower than it needs to be. 100 or even maybe 120(?) would be my personal preference.

Agreed on a line length limit of 100. My editor displays vertical lines on :80 and :100 already.

> * `46:1  error  Missing JSDoc comment                                require-jsdoc`: it's annoying, but probably valuable

Can we require jsdoc for anything that's public, but *not* require it for private methods? TS has visibility keywords that can help here.

> * ` 143:29  error  Expected an error object to be thrown                no-throw-literal`: haven't decided yet

We should adopt this.

**Comment by glennhartmann** [comment]
> > * `46:1  error  Missing JSDoc comment                                require-jsdoc`: it's annoying, but probably valuable
> 
> Can we require jsdoc for anything that's public, but _not_ require it for private methods? TS has visibility keywords that can help here.

[I don't think so](https://eslint.org/docs/rules/require-jsdoc)
