### ISSUE TITLE
images are cropped

### ISSUE THREAD

**Issue by glennhartmann** [GoogleChromeLabs/llaminator#70]
Since https://github.com/GoogleChromeLabs/llaminator/pull/52, I think.

<img width="1151" alt="Untitled" src="https://user-images.githubusercontent.com/570079/148701268-3e2e1b5c-bb8c-4e44-92f0-2b43170e137c.png">

**Comment by beverloo** [comment]
I like that PR #71 changes the background cropping, but not the size of the card. Part of discussion for the UI, but whatever we end up with, scrolling should be _somewhat_ predictable.
